export function buildProfileManagerPanelStyles(): string {
  return `
    :root{--bg:var(--vscode-editor-background);--soft:var(--vscode-editor-inactiveSelectionBackground);--strong:var(--vscode-editor-selectionBackground);--border:var(--vscode-panel-border);--text:var(--vscode-foreground);--muted:var(--vscode-descriptionForeground);--accent:var(--vscode-focusBorder);--btn:var(--vscode-button-background);--btn-fg:var(--vscode-button-foreground);--btn-hover:var(--vscode-button-hoverBackground);--btn2:var(--vscode-button-secondaryBackground);--btn2-fg:var(--vscode-button-secondaryForeground);--btn2-hover:var(--vscode-button-secondaryHoverBackground);--input-bg:var(--vscode-input-background);--input-fg:var(--vscode-input-foreground);--input-border:var(--vscode-input-border);--danger:var(--vscode-errorForeground);--badge-bg:var(--vscode-badge-background);--badge-fg:var(--vscode-badge-foreground);--shadow:rgba(0,0,0,.18);--shadow-strong:rgba(0,0,0,.28)}
    *{box-sizing:border-box}html,body{min-height:100%}body{margin:0;padding:28px;color:var(--text);font-family:var(--vscode-font-family);background:radial-gradient(circle at 0 0,var(--strong) 0,transparent 24%),radial-gradient(circle at 100% 0,rgba(0,120,212,.08) 0,transparent 22%),linear-gradient(180deg,var(--bg),var(--soft))}
    button,input{font:inherit}button{appearance:none}input{appearance:none}.shell{max-width:1280px;margin:0 auto;display:grid;gap:18px}
    .hero,.empty,.card,.pane{border:1px solid color-mix(in srgb,var(--border) 78%, transparent);background:linear-gradient(145deg,rgba(255,255,255,.025),rgba(255,255,255,.01));box-shadow:0 16px 42px var(--shadow)}
    .hero{display:grid;grid-template-columns:1fr;gap:18px;padding:28px;border-radius:26px;position:relative;overflow:hidden;align-items:start}
    .hero:before{content:'';position:absolute;inset:0;background:radial-gradient(circle at 100% 0,var(--strong) 0,transparent 26%);pointer-events:none}
    .eyebrow,.stat-label,.note-label,.section-label{margin:0 0 10px;color:var(--muted);font-size:.76rem;letter-spacing:.14em;text-transform:uppercase}
    .title{margin:0;font-size:clamp(1.9rem,3vw,3rem);line-height:1.02;max-width:14ch}.subtitle{margin:12px 0 0;color:var(--muted);line-height:1.7;max-width:60ch}
    .stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.stat{padding:16px 18px;border:1px solid color-mix(in srgb,var(--border) 78%, transparent);border-radius:18px;background:linear-gradient(180deg,rgba(255,255,255,.045),rgba(255,255,255,.015));min-width:0}.stat-value{font-size:1.1rem;font-weight:700;word-break:break-word}
    .toolbar{display:flex;justify-content:space-between;align-items:center;gap:14px}.toolbar-count{color:var(--muted)}.banner{display:none;padding:14px 16px;border:1px solid color-mix(in srgb,var(--border) 78%, transparent);border-radius:16px;background:rgba(255,255,255,.03)}.banner.active{display:block}
    .cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(340px,1fr));gap:16px;align-items:start}
    .card{padding:22px;border-radius:24px;position:relative;overflow:hidden;min-width:0}
    .card.active{border-color:var(--accent);box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--accent) 85%, transparent),0 16px 42px var(--shadow)}
    .top{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.name{margin:0 0 6px;font-size:1.1rem;font-weight:700;word-break:break-word}.provider-name{color:var(--muted);word-break:break-word}
    .desc{margin:14px 0 0;color:var(--muted);line-height:1.62;max-width:54ch}
    .pill{display:inline-flex;align-items:center;padding:5px 11px;border-radius:999px;background:var(--badge-bg);color:var(--badge-fg);font-size:.74rem;font-weight:600;white-space:nowrap}
    .meta,.notes,.actions{display:grid;gap:10px}.meta{margin:18px 0}.row{display:grid;grid-template-columns:minmax(88px,140px) minmax(0,1fr);gap:12px;padding:11px 14px;border-radius:14px;background:rgba(255,255,255,.03);min-width:0}.row .label{color:var(--muted)}.row .value{min-width:0;word-break:break-word;text-align:left}
    .note{padding:13px 14px;border-radius:16px;border:1px solid color-mix(in srgb,var(--border) 78%, transparent);background:rgba(255,255,255,.02)}.note-value{line-height:1.58}
    .empty{display:none;padding:42px 28px;border-radius:24px}.empty.active{display:block}.empty h2{margin:0 0 10px;font-size:1.45rem}.empty p{margin:0 0 18px;color:var(--muted);line-height:1.7;max-width:58ch}
    .btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;min-height:42px;padding:10px 16px;border:1px solid transparent;border-radius:12px;cursor:pointer;transition:background .14s ease,border-color .14s ease,transform .14s ease;background:var(--btn2);color:var(--btn2-fg)}.btn:hover{background:var(--btn2-hover);transform:translateY(-1px)}.btn.primary{background:var(--btn);color:var(--btn-fg)}.btn.primary:hover{background:var(--btn-hover)}.btn.danger{background:transparent;color:var(--danger);border-color:rgba(255,0,0,.24)}.btn.small{min-height:35px;padding:8px 12px;border-radius:10px;font-size:.88rem}
    .overlay{display:none;position:fixed;inset:0;padding:24px;background:rgba(0,0,0,.78);align-items:center;justify-content:center;z-index:10;backdrop-filter:blur(8px)}.overlay.active{display:flex}
    .modal{width:min(1180px,calc(100vw - 48px));max-height:92vh;overflow:auto;padding:24px;border:1px solid color-mix(in srgb,var(--border) 82%, transparent);border-radius:30px;background:linear-gradient(180deg,color-mix(in srgb,var(--bg) 94%, black 6%),color-mix(in srgb,var(--bg) 90%, black 10%));box-shadow:0 30px 70px var(--shadow-strong);position:relative}
    .close{position:absolute;right:18px;top:18px;width:42px;height:42px;border-radius:999px;border:1px solid color-mix(in srgb,var(--border) 82%, transparent);background:rgba(255,255,255,.08);color:var(--text);cursor:pointer}
    .modal-head{padding-right:52px;margin-bottom:18px}.modal-head h2{margin:0;font-size:1.48rem}.modal-head p{margin:8px 0 0;color:var(--muted);line-height:1.62;max-width:64ch}
    .modal-grid{display:grid;grid-template-columns:minmax(320px,380px) minmax(0,1fr);gap:18px;align-items:start}.modal-grid>*{min-width:0}
    .pane{padding:18px;border-radius:24px;min-width:0;background:linear-gradient(180deg,rgba(255,255,255,.07),rgba(255,255,255,.04));border:1px solid color-mix(in srgb,var(--border) 84%, transparent)}.pane-form{position:sticky;top:0}.hint{margin-top:8px;color:var(--muted);font-size:.84rem;line-height:1.55}
    .providers{display:flex;flex-direction:column;gap:12px;max-height:62vh;overflow:auto;padding-right:4px;margin-top:14px;scrollbar-width:thin}
    .provider{display:grid;gap:8px;width:100%;padding:16px 17px;border:1px solid color-mix(in srgb,var(--border) 82%, transparent);border-radius:18px;background:rgba(255,255,255,.06);color:var(--text);text-align:left;cursor:pointer;min-width:0}
    .provider:hover{border-color:color-mix(in srgb,var(--accent) 55%, var(--border));background:rgba(255,255,255,.09)}
    .provider.active{border-color:var(--accent);background:linear-gradient(180deg,rgba(0,120,212,.2),rgba(255,255,255,.09));box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--accent) 65%, transparent)}
    .provider-title{font-size:1rem;font-weight:700;word-break:break-word}.provider-desc,.provider-aud,.provider-end{min-width:0;overflow-wrap:anywhere}.provider-desc,.provider-aud{color:var(--muted);line-height:1.54}.provider-end{display:block;padding:6px 10px;border:1px solid color-mix(in srgb,var(--border) 86%, transparent);border-radius:999px;color:var(--muted);font-size:.76rem;line-height:1.45;background:rgba(255,255,255,.09)}
    .error{display:none;margin-bottom:12px;padding:12px 14px;border:1px solid rgba(255,0,0,.25);border-radius:14px;background:rgba(255,0,0,.06);color:var(--danger)}.error.active{display:block}
    .field{margin-bottom:16px}.field label{display:block;margin-bottom:8px;font-weight:600}.field input{width:100%;padding:12px 13px;border:1px solid var(--input-border);border-radius:14px;background:var(--input-bg);color:var(--input-fg)}.field input:focus{outline:1px solid var(--accent);border-color:var(--accent)}.actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}
    @media (max-width:960px){body{padding:20px}.stats{grid-template-columns:1fr}.modal{width:min(960px,calc(100vw - 32px));padding:20px}.modal-grid{grid-template-columns:1fr}.pane-form{position:static}.providers{max-height:none}}
    @media (max-width:640px){body{padding:16px}.hero,.modal,.empty,.card,.pane{padding:20px}.toolbar{flex-direction:column;align-items:stretch}.top{flex-direction:column;align-items:flex-start}}
  `;
}
